---
- hosts: all

  roles:
    - ansistrano.deploy

  vars_files:
    - inventories/production/group_vars/provision_vault.yml
    - vars/vars.yml
    - vars/deploy_vars.yml

  vars:
    ansistrano_deploy_via: "rsync"
    ansistrano_rsync_extra_params:
      - "--exclude='.ddev/'"
      - "--exclude='.DS_Store'"
      - "--exclude='.editorconfig'"
      - "--exclude='.git'"
      - "--exclude='.gitattributes'"
      - "--exclude='.gitignore'"
      - "--exclude='vault_pass.txt'"
      - "--exclude='installer.sh'"
      - "--exclude='LICENSE'"
      - "--exclude='.prettierrc'"
      - "--exclude='README.md'"
      - "--exclude='bitbucket-pipelines.yml'"
      - "--exclude='.vscode'"
      - "--exclude='web/sites/default/files'"
      - "--exclude='web/themes/custom/{{ vault_theme_name }}/node_modules'"
      - "--exclude='web/sites/default/settings.ddev.php'"
      - "--exclude='web/sites/default/settings.local.php'"

    ansistrano_deploy_from: "{{ playbook_dir }}/../../"
    ansistrano_deploy_to: "{{ project_deploy_path }}"
    ansistrano_keep_releases: "{{ vault_keep_releases }}"

    # Hooks
    ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/before-symlink-shared-tasks.yml"
    ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/tasks/after-update-code-tasks.yml"
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/tasks/before-symlink-tasks.yml"
    ansistrano_before_cleanup_tasks_file: "{{ playbook_dir }}/tasks/before-cleanup-tasks.yml"

    ansistrano_shared_paths:
      - "web/sites/default/files"

    ansistrano_shared_files:
      - "web/sites/default/settings.live.php"
