---
- name: Check if Drupal is installed
  stat:
    path: "{{ project_deploy_path }}/current/web" # Specify the path where Drupal is typically installed
  register: drupal_installed

- name: Install Drupal using Drush
  shell: |
    {{ release_drush_path }} site-install -y \
    --db-url=mysql://{{ vault_database_user }}:{{ vault_database_password }}@localhost/{{ vault_database_name }} \
    --account-name={{ vault_account_drupal_name }} \
    --account-pass={{ vault_account_drupal_pass }} \
    --site-name={{ vault_account_drupal_site_name }} \
    --yes
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  when: drupal_installed.stat.exists == false

- name: Print if Drupal is installed
  debug:
    msg: "Drupal is installed ==>: {{  drupal_installed.stat.exists }}"

- name: Post-update tasks
  when: drupal_installed.stat.exists == true
  block:
    - name: Clear Drush cache
      command: >
        {{ release_drush_path }}
        cache-clear drush
        chdir={{ release_drupal_path }}
      changed_when: false

    - name: Run database updates
      command: >
        {{ release_drush_path }}
        updatedb -y
        chdir={{ release_drupal_path }}
      register: update_database_output
      changed_when: "'No pending updates' not in update_database_output.stderr"

    - name: Import configuration
      command: >
        {{ release_drush_path }}
        config-import -y
        chdir={{ release_drupal_path }}
      register: config_import_output
      changed_when: "'There are no changes to import' not in config_import_output.stderr"

    - name: Rebuild cache
      command: >
        {{ release_drush_path }} cache-rebuild
        chdir={{ release_drupal_path }}
      changed_when: false
