---
- name: Print Ansistrano Release Path
  debug:
    msg: "Ansistrano Release Path: {{ ansistrano_release_path.stdout }}"

- name: Install Drupal dependencies with Composer
  shell: composer install
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_release_path.stdout }}/vendor/autoload.php"
