---
- name: Install Composer dependencies
  composer:
    command: install
    optimize_autoloader: true
    working_dir: '{{ ansistrano_release_path.stdout }}'

- name: Generate settings.php file
  include_role:
    name: opdavies.drupal_settings_files
