- name: deploying project
  hosts: all
  remote_user: and_stage
  become: true
  tasks:
    - include_vars:
        file: vars.yml
    - include_vars:
        file: secrets.yml
    - include_role:
        name: ansistrano.deploy
